### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_os_get_passwd

### ISSUE THREAD

**Issue by atian25** [node-modules/node-homedir#2]
node v6.9.0

```
Error: ENOENT: no such file or directory, uv_os_get_passwd
    at Error (native)
    at module.exports (/usr/local/lib/node_modules/.egg-init_npminstall/node_modules/.1.0.0@node-homedir/index.js:6:25)
    at Command.getRegistryByType (/usr/local/lib/node_modules/.egg-init_npminstall/node_modules/.1.5.0@egg-init/lib/init_command.js:271:24)
    at Command.run (/usr/local/lib/node_modules/.egg-init_npminstall/node_modules/.1.5.0@egg-init/lib/init_command.js:44:29)
```
---
```
> os.userInfo
[Function: getUserInfo]
> os.userInfo()
Error: ENOENT: no such file or directory, uv_os_get_passwd
    at Error (native)
    at repl:1:4
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
```

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/20468147/58791576-afce-11e6-9f41-c51174c67f8e.png)

**Comment by ngot** [comment]
"mac 好像是有死机自动重启了下，估计是启动不完整，环境变量啥的"
